--------------------------------------------------------
--  File created - Thursday-August-24-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TB_CLIENTE_CINE
--------------------------------------------------------

  CREATE TABLE "ESTUDIANTE"."TB_CLIENTE_CINE" 
   (	"IDENT" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"APELLIDO_PATERNO" VARCHAR2(100 BYTE), 
	"APELLIDO_MATERNO" VARCHAR2(100 BYTE), 
	"PELICULA" VARCHAR2(100 BYTE), 
	"RESERVA" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TB_PELICULAS
--------------------------------------------------------

  CREATE TABLE "ESTUDIANTE"."TB_PELICULAS" 
   (	"NOMBRE_PELICULA" VARCHAR2(100 BYTE), 
	"HORA_RESERVA" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TB_PRODUCTOS
--------------------------------------------------------

  CREATE TABLE "ESTUDIANTE"."TB_PRODUCTOS" 
   (	"ID_PRODUCTO" NUMBER(10,2), 
	"NOMBRE_PROD" VARCHAR2(50 BYTE), 
	"PRECIO_PROD" NUMBER(10,2), 
	"TIPO_PROD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TB_SALAS
--------------------------------------------------------

  CREATE TABLE "ESTUDIANTE"."TB_SALAS" 
   (	"NOMBRE_ASIENTO" VARCHAR2(50 BYTE), 
	"RESERVADO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ESTUDIANTE.TB_CLIENTE_CINE
SET DEFINE OFF;
Insert into ESTUDIANTE.TB_CLIENTE_CINE (IDENT,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,PELICULA,RESERVA) values (11310760,'Maria','Salas','Telmo','JOHNWICK3','15:30');
Insert into ESTUDIANTE.TB_CLIENTE_CINE (IDENT,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,PELICULA,RESERVA) values (12216780,'Fernando','Suarez','Mora','BARBIE','10:00');
Insert into ESTUDIANTE.TB_CLIENTE_CINE (IDENT,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,PELICULA,RESERVA) values (12340422,'Laura','Salgado','Odio','JOHNWICK3','15:30');
Insert into ESTUDIANTE.TB_CLIENTE_CINE (IDENT,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,PELICULA,RESERVA) values (11310760,'Mario','Sanchez','Zuniga','BARBIE','10:00');
Insert into ESTUDIANTE.TB_CLIENTE_CINE (IDENT,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,PELICULA,RESERVA) values (12216780,'Rebecca','Lindo','Diaz','OPPENHEIMER','12:30');
Insert into ESTUDIANTE.TB_CLIENTE_CINE (IDENT,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,PELICULA,RESERVA) values (12340422,'German','Lopez','Medrano','OPPENHEIMER','12:30');
REM INSERTING into ESTUDIANTE.TB_PELICULAS
SET DEFINE OFF;
Insert into ESTUDIANTE.TB_PELICULAS (NOMBRE_PELICULA,HORA_RESERVA) values ('BARBIE','10:00');
Insert into ESTUDIANTE.TB_PELICULAS (NOMBRE_PELICULA,HORA_RESERVA) values ('OPPENHEIMER','12:30');
Insert into ESTUDIANTE.TB_PELICULAS (NOMBRE_PELICULA,HORA_RESERVA) values ('JOHNWICK3','15:30');
Insert into ESTUDIANTE.TB_PELICULAS (NOMBRE_PELICULA,HORA_RESERVA) values ('TERMINATOR5','17:40');
Insert into ESTUDIANTE.TB_PELICULAS (NOMBRE_PELICULA,HORA_RESERVA) values ('FALLOUT','20:20');
Insert into ESTUDIANTE.TB_PELICULAS (NOMBRE_PELICULA,HORA_RESERVA) values ('TARZAN4','21:40');
Insert into ESTUDIANTE.TB_PELICULAS (NOMBRE_PELICULA,HORA_RESERVA) values ('RAPIDOSYFURIOSOS17','23:00');
REM INSERTING into ESTUDIANTE.TB_PRODUCTOS
SET DEFINE OFF;
Insert into ESTUDIANTE.TB_PRODUCTOS (ID_PRODUCTO,NOMBRE_PROD,PRECIO_PROD,TIPO_PROD) values (1,'PALOMITAS',6500,'COMIDA');
Insert into ESTUDIANTE.TB_PRODUCTOS (ID_PRODUCTO,NOMBRE_PROD,PRECIO_PROD,TIPO_PROD) values (2,'GASEOSA',3500,'BEBIDA');
Insert into ESTUDIANTE.TB_PRODUCTOS (ID_PRODUCTO,NOMBRE_PROD,PRECIO_PROD,TIPO_PROD) values (3,'NACHOS',4500,'COMIDA');
Insert into ESTUDIANTE.TB_PRODUCTOS (ID_PRODUCTO,NOMBRE_PROD,PRECIO_PROD,TIPO_PROD) values (4,'PERRO_CALIENTE',5500,'COMIDA');
Insert into ESTUDIANTE.TB_PRODUCTOS (ID_PRODUCTO,NOMBRE_PROD,PRECIO_PROD,TIPO_PROD) values (5,'TE_FRIO',3200,'BEBIDA');
REM INSERTING into ESTUDIANTE.TB_SALAS
SET DEFINE OFF;
Insert into ESTUDIANTE.TB_SALAS (NOMBRE_ASIENTO,RESERVADO) values ('A1','DISPONIBLE');
Insert into ESTUDIANTE.TB_SALAS (NOMBRE_ASIENTO,RESERVADO) values ('A2','DISPONIBLE');
Insert into ESTUDIANTE.TB_SALAS (NOMBRE_ASIENTO,RESERVADO) values ('A3','DISPONIBLE');
Insert into ESTUDIANTE.TB_SALAS (NOMBRE_ASIENTO,RESERVADO) values ('A4','DISPONIBLE');
Insert into ESTUDIANTE.TB_SALAS (NOMBRE_ASIENTO,RESERVADO) values ('A5','DISPONIBLE');
Insert into ESTUDIANTE.TB_SALAS (NOMBRE_ASIENTO,RESERVADO) values ('B1','DISPONIBLE');
Insert into ESTUDIANTE.TB_SALAS (NOMBRE_ASIENTO,RESERVADO) values ('B2','DISPONIBLE');
Insert into ESTUDIANTE.TB_SALAS (NOMBRE_ASIENTO,RESERVADO) values ('B3','DISPONIBLE');
Insert into ESTUDIANTE.TB_SALAS (NOMBRE_ASIENTO,RESERVADO) values ('B4','DISPONIBLE');
Insert into ESTUDIANTE.TB_SALAS (NOMBRE_ASIENTO,RESERVADO) values ('B5','DISPONIBLE');
Insert into ESTUDIANTE.TB_SALAS (NOMBRE_ASIENTO,RESERVADO) values ('C1','DISPONIBLE');
Insert into ESTUDIANTE.TB_SALAS (NOMBRE_ASIENTO,RESERVADO) values ('C2','DISPONIBLE');
Insert into ESTUDIANTE.TB_SALAS (NOMBRE_ASIENTO,RESERVADO) values ('C3','DISPONIBLE');
Insert into ESTUDIANTE.TB_SALAS (NOMBRE_ASIENTO,RESERVADO) values ('C4','DISPONIBLE');
Insert into ESTUDIANTE.TB_SALAS (NOMBRE_ASIENTO,RESERVADO) values ('C5','DISPONIBLE');
Insert into ESTUDIANTE.TB_SALAS (NOMBRE_ASIENTO,RESERVADO) values ('D1','DISPONIBLE');
Insert into ESTUDIANTE.TB_SALAS (NOMBRE_ASIENTO,RESERVADO) values ('D2','DISPONIBLE');
Insert into ESTUDIANTE.TB_SALAS (NOMBRE_ASIENTO,RESERVADO) values ('D3','DISPONIBLE');
Insert into ESTUDIANTE.TB_SALAS (NOMBRE_ASIENTO,RESERVADO) values ('D4','DISPONIBLE');
Insert into ESTUDIANTE.TB_SALAS (NOMBRE_ASIENTO,RESERVADO) values ('D5','DISPONIBLE');
